name: assignment4
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  contacts_service: ^0.6.1
  permission_handler: ^10.0.0
  image_picker: ^0.8.4+4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.6.0


flutter:
  assets:
    - assets/

